name = "ContinuousWavelet"
uuid = "f4805cc5-8dd6-48ca-a5e0-9d6fc2d45b8d"
authors = ["Hannes Matuschek <hannes.matuschek@uni-potsdam.de>"]
version = "0.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
